/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyOtpRouteImport } from './routes/verify-otp'
import { Route as RoleSelectionRouteImport } from './routes/role-selection'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardSimulationRouteImport } from './routes/_dashboard.simulation'
import { Route as DashboardSettingsRouteImport } from './routes/_dashboard.settings'
import { Route as DashboardRiskMapRouteImport } from './routes/_dashboard.risk-map'
import { Route as DashboardResourcesRouteImport } from './routes/_dashboard.resources'
import { Route as DashboardReportsRouteImport } from './routes/_dashboard.reports'
import { Route as DashboardOverviewRouteImport } from './routes/_dashboard.overview'
import { Route as DashboardEvacuationRouteImport } from './routes/_dashboard.evacuation'
import { Route as DashboardEarthquakesRouteImport } from './routes/_dashboard.earthquakes'
import { Route as DashboardAlertsRouteImport } from './routes/_dashboard.alerts'
import { Route as ApiPublicTelegramWebhookRouteImport } from './routes/api/public/telegram/webhook'
import { Route as ApiPublicHooksAutoAlertsRouteImport } from './routes/api/public/hooks/auto-alerts'

const VerifyOtpRoute = VerifyOtpRouteImport.update({
  id: '/verify-otp',
  path: '/verify-otp',
  getParentRoute: () => rootRouteImport,
} as any)
const RoleSelectionRoute = RoleSelectionRouteImport.update({
  id: '/role-selection',
  path: '/role-selection',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSimulationRoute = DashboardSimulationRouteImport.update({
  id: '/simulation',
  path: '/simulation',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRiskMapRoute = DashboardRiskMapRouteImport.update({
  id: '/risk-map',
  path: '/risk-map',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardResourcesRoute = DashboardResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardReportsRoute = DashboardReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOverviewRoute = DashboardOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEvacuationRoute = DashboardEvacuationRouteImport.update({
  id: '/evacuation',
  path: '/evacuation',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEarthquakesRoute = DashboardEarthquakesRouteImport.update({
  id: '/earthquakes',
  path: '/earthquakes',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAlertsRoute = DashboardAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiPublicTelegramWebhookRoute =
  ApiPublicTelegramWebhookRouteImport.update({
    id: '/api/public/telegram/webhook',
    path: '/api/public/telegram/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksAutoAlertsRoute =
  ApiPublicHooksAutoAlertsRouteImport.update({
    id: '/api/public/hooks/auto-alerts',
    path: '/api/public/hooks/auto-alerts',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/role-selection': typeof RoleSelectionRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/alerts': typeof DashboardAlertsRoute
  '/earthquakes': typeof DashboardEarthquakesRoute
  '/evacuation': typeof DashboardEvacuationRoute
  '/overview': typeof DashboardOverviewRoute
  '/reports': typeof DashboardReportsRoute
  '/resources': typeof DashboardResourcesRoute
  '/risk-map': typeof DashboardRiskMapRoute
  '/settings': typeof DashboardSettingsRoute
  '/simulation': typeof DashboardSimulationRoute
  '/api/public/hooks/auto-alerts': typeof ApiPublicHooksAutoAlertsRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/role-selection': typeof RoleSelectionRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/alerts': typeof DashboardAlertsRoute
  '/earthquakes': typeof DashboardEarthquakesRoute
  '/evacuation': typeof DashboardEvacuationRoute
  '/overview': typeof DashboardOverviewRoute
  '/reports': typeof DashboardReportsRoute
  '/resources': typeof DashboardResourcesRoute
  '/risk-map': typeof DashboardRiskMapRoute
  '/settings': typeof DashboardSettingsRoute
  '/simulation': typeof DashboardSimulationRoute
  '/api/public/hooks/auto-alerts': typeof ApiPublicHooksAutoAlertsRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/role-selection': typeof RoleSelectionRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/_dashboard/alerts': typeof DashboardAlertsRoute
  '/_dashboard/earthquakes': typeof DashboardEarthquakesRoute
  '/_dashboard/evacuation': typeof DashboardEvacuationRoute
  '/_dashboard/overview': typeof DashboardOverviewRoute
  '/_dashboard/reports': typeof DashboardReportsRoute
  '/_dashboard/resources': typeof DashboardResourcesRoute
  '/_dashboard/risk-map': typeof DashboardRiskMapRoute
  '/_dashboard/settings': typeof DashboardSettingsRoute
  '/_dashboard/simulation': typeof DashboardSimulationRoute
  '/api/public/hooks/auto-alerts': typeof ApiPublicHooksAutoAlertsRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/reset-password'
    | '/role-selection'
    | '/verify-otp'
    | '/alerts'
    | '/earthquakes'
    | '/evacuation'
    | '/overview'
    | '/reports'
    | '/resources'
    | '/risk-map'
    | '/settings'
    | '/simulation'
    | '/api/public/hooks/auto-alerts'
    | '/api/public/telegram/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/reset-password'
    | '/role-selection'
    | '/verify-otp'
    | '/alerts'
    | '/earthquakes'
    | '/evacuation'
    | '/overview'
    | '/reports'
    | '/resources'
    | '/risk-map'
    | '/settings'
    | '/simulation'
    | '/api/public/hooks/auto-alerts'
    | '/api/public/telegram/webhook'
  id:
    | '__root__'
    | '/'
    | '/_dashboard'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/reset-password'
    | '/role-selection'
    | '/verify-otp'
    | '/_dashboard/alerts'
    | '/_dashboard/earthquakes'
    | '/_dashboard/evacuation'
    | '/_dashboard/overview'
    | '/_dashboard/reports'
    | '/_dashboard/resources'
    | '/_dashboard/risk-map'
    | '/_dashboard/settings'
    | '/_dashboard/simulation'
    | '/api/public/hooks/auto-alerts'
    | '/api/public/telegram/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RoleSelectionRoute: typeof RoleSelectionRoute
  VerifyOtpRoute: typeof VerifyOtpRoute
  ApiPublicHooksAutoAlertsRoute: typeof ApiPublicHooksAutoAlertsRoute
  ApiPublicTelegramWebhookRoute: typeof ApiPublicTelegramWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-otp': {
      id: '/verify-otp'
      path: '/verify-otp'
      fullPath: '/verify-otp'
      preLoaderRoute: typeof VerifyOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/role-selection': {
      id: '/role-selection'
      path: '/role-selection'
      fullPath: '/role-selection'
      preLoaderRoute: typeof RoleSelectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/simulation': {
      id: '/_dashboard/simulation'
      path: '/simulation'
      fullPath: '/simulation'
      preLoaderRoute: typeof DashboardSimulationRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/settings': {
      id: '/_dashboard/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/risk-map': {
      id: '/_dashboard/risk-map'
      path: '/risk-map'
      fullPath: '/risk-map'
      preLoaderRoute: typeof DashboardRiskMapRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/resources': {
      id: '/_dashboard/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof DashboardResourcesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/reports': {
      id: '/_dashboard/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof DashboardReportsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/overview': {
      id: '/_dashboard/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof DashboardOverviewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/evacuation': {
      id: '/_dashboard/evacuation'
      path: '/evacuation'
      fullPath: '/evacuation'
      preLoaderRoute: typeof DashboardEvacuationRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/earthquakes': {
      id: '/_dashboard/earthquakes'
      path: '/earthquakes'
      fullPath: '/earthquakes'
      preLoaderRoute: typeof DashboardEarthquakesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/alerts': {
      id: '/_dashboard/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof DashboardAlertsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/public/telegram/webhook': {
      id: '/api/public/telegram/webhook'
      path: '/api/public/telegram/webhook'
      fullPath: '/api/public/telegram/webhook'
      preLoaderRoute: typeof ApiPublicTelegramWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/auto-alerts': {
      id: '/api/public/hooks/auto-alerts'
      path: '/api/public/hooks/auto-alerts'
      fullPath: '/api/public/hooks/auto-alerts'
      preLoaderRoute: typeof ApiPublicHooksAutoAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardAlertsRoute: typeof DashboardAlertsRoute
  DashboardEarthquakesRoute: typeof DashboardEarthquakesRoute
  DashboardEvacuationRoute: typeof DashboardEvacuationRoute
  DashboardOverviewRoute: typeof DashboardOverviewRoute
  DashboardReportsRoute: typeof DashboardReportsRoute
  DashboardResourcesRoute: typeof DashboardResourcesRoute
  DashboardRiskMapRoute: typeof DashboardRiskMapRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardSimulationRoute: typeof DashboardSimulationRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAlertsRoute: DashboardAlertsRoute,
  DashboardEarthquakesRoute: DashboardEarthquakesRoute,
  DashboardEvacuationRoute: DashboardEvacuationRoute,
  DashboardOverviewRoute: DashboardOverviewRoute,
  DashboardReportsRoute: DashboardReportsRoute,
  DashboardResourcesRoute: DashboardResourcesRoute,
  DashboardRiskMapRoute: DashboardRiskMapRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardSimulationRoute: DashboardSimulationRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RoleSelectionRoute: RoleSelectionRoute,
  VerifyOtpRoute: VerifyOtpRoute,
  ApiPublicHooksAutoAlertsRoute: ApiPublicHooksAutoAlertsRoute,
  ApiPublicTelegramWebhookRoute: ApiPublicTelegramWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
